#!/bin/sh

#attivazioni erronee
if ./ztl ; then
    return 1
fi

if ./ztl filemulte file2 ; then
    return 1
fi

if ./permserver ; then
    return 1
fi

if ./permserver filepermessi1 filepermessi2 ; then
    return 1
fi

if ./permserver filepermessi1 ; then
    return 1
fi

# file dati scorretto
if ./permserver perm.dat ; then
    return 1
fi

# file dati OK
./permserver perm1.dat &
./passaggi | ./ztl multe.log &

#lasciamo eseguire 5 secondi
sleep 5

#uccidiamo il server
if ! killall -w permserver ; then
    echo Nessun permserver attivo.
fi

# attandiamo la terminazione di ztl
killall -w ztl
