#!/bin/sh

#test riconoscimento multe
./permserver perm1.dat &
./passaggi 42 1000000 10 | ./ztl multe.log 

sort multe.log > multe1.log

if ! diff multe1.log multe1.sort.check ; then
    echo Errore generazione multe 1
    exit 1
fi


#test generazione piu' veloce
./passaggi 42 10000 100 | ./ztl multe.log

sort multe.log > multe2.log

if ! diff multe2.log multe2.sort.check ; then
    echo Errore generazione multe 2
    exit 1
fi


#test generazione ancora piu' veloce
echo "##################################" 1&>2
./passaggi 42 10 100 | ./ztl multe.log 

sort multe.log > multe3.log

if ! diff multe3.log multe2.sort.check ; then
    echo Errore generazione multe 3
    exit 1
fi

# test con sequenze diverse
#test generazione ancora piu' veloce
echo "##################################" 1&>2
./passaggi 4200 100000 10 | ./ztl multe.log 

sort multe.log > multe3.log

if ! diff multe3.log multe3.sort.check ; then
    echo Errore generazione multe 5
    exit 1
fi


# test con sequenze diverse
#test generazione ancora piu' veloce
echo "##################################" 1&>2
./passaggi 4200 10 10 | ./ztl multe.log 

sort multe.log > multe3.log

if ! diff multe3.log multe3.sort.check ; then
    echo Errore generazione multe 6
    exit 1
fi

if ! killall -w -TERM permserver ; then
    exit 1
fi

exit 0
